"""add email_verificado and drop legacy confirmacao columns

Revision ID: 0b8cb6d25901
Revises: b2c3d4e5f6a7
Create Date: 2026-06-14 16:01:49.748938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b8cb6d25901'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('email_verificado', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('usuarios', 'email_verificado', server_default=None)
    op.drop_constraint(op.f('usuarios_confirmacao_token_key'), 'usuarios', type_='unique')
    op.drop_column('usuarios', 'confirmacao_expira_em')
    op.drop_column('usuarios', 'confirmacao_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('confirmacao_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('usuarios', sa.Column('confirmacao_expira_em', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('usuarios_confirmacao_token_key'), 'usuarios', ['confirmacao_token'], postgresql_nulls_not_distinct=False)
    op.drop_column('usuarios', 'email_verificado')
    # ### end Alembic commands ###
