"""adiciona geolocalizacao opcional ao evento

Revision ID: 1e3f35c8c53e
Revises: 0b8cb6d25901
Create Date: 2026-06-14 16:57:01.538084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e3f35c8c53e'
down_revision: Union[str, Sequence[str], None] = '0b8cb6d25901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventos', sa.Column('endereco_completo', sa.String(length=500), nullable=True))
    op.add_column('eventos', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('eventos', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eventos', 'longitude')
    op.drop_column('eventos', 'latitude')
    op.drop_column('eventos', 'endereco_completo')
    # ### end Alembic commands ###
